about: {home: 'http://scitools.org.uk/iris', license: Open Government License (UK)}
build:
  entry_points: []
  features: []
  number: 0
  string: ''
  track_features: []
package: {name: iris, version: 1.7.0}
requirements:
  build: [python, biggus, numpy, scipy, udunits2, netcdf4, pyke, cartopy, geos, nose,
    setuptools]
  conflicts: []
  run: [python, biggus, numpy, scipy, udunits2, netcdf4, geos, pyke, cartopy, shapely,
    matplotlib]
source:
  git_branch: ''
  git_tag: v1.7.0
  git_url: https://github.com/SciTools/iris.git
  md5: ''
  patches: []
  svn_rev: ''
test:
  commands: []
  files: []
  imports: []
  requires: []
