package:
  name: owslib
  version: !!str 0.8.7

source:

  git_url: https://github.com/geopython/OWSLib.git
  git_tag: 0.8.7

requirements:
  build:
    - python
    - setuptools
    - dateutil
    - pytz

  run:
    - python
    - dateutil
    - pytz

test:
  # Python imports
  imports:
    - owslib.coverage
    - owslib.waterml
    - owslib.swe.observation
    - owslib.swe.sensor
    - owslib
    - owslib.feature
    - owslib.swe

about:
  home: https://geopython.github.io/OWSLib
  license: BSD License
  summary: 'OGC Web Service utility library'
