package:
    name: udunits2
    version: 2.2.17

source:
    fn: udunits-2.2.17.tar.gz
    url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.17.tar.gz
    sha1: 80a7f9802fba5a09d7828646d9845bc677b97a39

build:
    number: 0

test:
    commands:
        - udunits2 -h

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  summary: The UDUNITS package supports units of physical quantities.
