package:
  name: iris
  version: !!str 1.7.2
source:
  git_url: https://github.com/SciTools/iris.git
  git_tag: v1.7.2

requirements:
  build:
    - python
    - biggus
    - numpy
    - scipy
    - udunits2
    - netcdf4
    - pyke
    - cartopy
    - geos
    - nose
    - setuptools
  run:
    - python
    - biggus
    - numpy
    - scipy
    - udunits2
    - netcdf4
    - geos
    - pyke
    - cartopy
    - shapely
    - matplotlib

test:
  imports:
    - iris

about:
  home: http://scitools.org.uk/iris
  license: Open Government License (UK)
  summary: 'Library for analysing and visualising meteorological and oceanographic data sets'

